import { FormEvent, useState } from 'react'
import { useAuth } from '../context/AuthContext'
import { supabase } from '../lib/supabase'
import { uploadMedia } from '../lib/storage'
import { Camera, Lock, Save } from 'lucide-react'

export default function Account(){
 const {profile}=useAuth(); const [name,setName]=useState(profile?.full_name||''); const [file,setFile]=useState<File|null>(null); const [avatar,setAvatar]=useState(profile?.avatar_url||''); const [password,setPassword]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false)
 async function save(e:FormEvent){e.preventDefault();if(!profile)return;setBusy(true);setMessage('');try{let avatarUrl=avatar;if(file)avatarUrl=await uploadMedia(file,'profiles');const{error}=await supabase.from('profiles').update({full_name:name,avatar_url:avatarUrl||null,updated_at:new Date().toISOString()}).eq('id',profile.id);if(error)throw error;if(password){if(password.length<8)throw new Error('Password must be at least 8 characters.');const{error:pw}=await supabase.auth.updateUser({password});if(pw)throw pw;setPassword('')}setAvatar(avatarUrl);setMessage('Account updated successfully.')}catch(err){setMessage(err instanceof Error?err.message:'Unable to update account')}finally{setBusy(false)}}
 return <div><h1 className="text-2xl font-bold">My Account</h1><p className="text-slate-500 mt-1">Manage your administrator profile, photo and password.</p><form onSubmit={save} className="mt-6 max-w-2xl space-y-6"><div className="bg-white border rounded-xl p-6"><div className="flex items-center gap-4"><div className="w-20 h-20 rounded-full overflow-hidden bg-slate-100 grid place-items-center">{avatar?<img src={avatar} className="w-full h-full object-cover"/>:<span className="text-2xl font-semibold text-slate-400">{(name||profile?.email||'A').charAt(0).toUpperCase()}</span>}</div><label className="cursor-pointer inline-flex items-center gap-2 border rounded-lg px-3 py-2 text-sm"><Camera size={16}/> Change photo<input hidden type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div><label className="block text-sm mt-5">Full name<input className="mt-1 w-full border rounded-lg px-3 py-2.5" value={name} onChange={e=>setName(e.target.value)}/></label><div className="mt-4 text-sm"><span className="text-slate-500">Email:</span> {profile?.email}</div><div className="mt-2 text-sm"><span className="text-slate-500">Role:</span> {profile?.role?.replace('_',' ')}</div></div><div className="bg-white border rounded-xl p-6"><h2 className="font-semibold flex items-center gap-2"><Lock size={17}/> Change password</h2><p className="text-xs text-slate-500 mt-1">Leave blank if you do not want to change it.</p><input type="password" minLength={8} placeholder="New password (8+ characters)" value={password} onChange={e=>setPassword(e.target.value)} className="mt-4 w-full border rounded-lg px-3 py-2.5"/></div>{message&&<div className="p-3 rounded-lg border bg-slate-50 text-sm">{message}</div>}<button disabled={busy} className="bg-blue-700 text-white px-4 py-2.5 rounded-lg flex items-center gap-2 disabled:opacity-50"><Save size={17}/>{busy?'Saving…':'Save changes'}</button></form></div>
}
