import { useEffect, useMemo, useState } from 'react'
import { RefreshCw, ShieldCheck } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { GivingTransaction } from '../types'

export default function Giving(){
 const [rows,setRows]=useState<GivingTransaction[]>([]); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(''); const [verifying,setVerifying]=useState<string|null>(null)
 async function load(){setLoading(true);const{data,error}=await supabase.from('giving_transactions').select('*').order('created_at',{ascending:false}).limit(200);if(error)setMessage(error.message);setRows((data??[]) as GivingTransaction[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const successful=useMemo(()=>rows.filter(x=>['success','paid'].includes(String(x.status).toLowerCase())),[rows]); const failed=useMemo(()=>rows.filter(x=>['failed','cancelled','abandoned'].includes(String(x.status).toLowerCase())),[rows]); const pending=useMemo(()=>rows.filter(x=>!['success','paid','failed','cancelled','abandoned'].includes(String(x.status).toLowerCase())),[rows]); const totalNgn=successful.filter(x=>x.currency==='NGN').reduce((a,x)=>a+Number(x.amount),0)
 async function verify(reference:string){setVerifying(reference);setMessage('');const{data,error}=await supabase.functions.invoke('paystack-verify',{body:{reference}});if(error||data?.error)setMessage(error?.message||data?.error||'Verification failed');else setMessage(`Payment ${reference} is ${data.status}.`);await load();setVerifying(null)}
 return <div><div className="flex justify-between items-center mb-6"><div><h1 className="text-2xl font-bold">Giving</h1><p className="text-slate-500 mt-1">Paystack transactions and verified giving history.</p></div><button onClick={load} className="px-3 py-2 border rounded-lg flex gap-2 items-center"><RefreshCw size={16}/> Refresh</button></div>
 {message&&<div className="mb-5 p-3 rounded-lg bg-slate-50 border text-sm">{message}</div>}
 <div className="grid sm:grid-cols-4 gap-4 my-5"><div className="bg-white border rounded-xl p-5"><div className="text-sm text-slate-500">Successful NGN</div><div className="text-2xl font-bold mt-2">₦{totalNgn.toLocaleString()}</div></div><div className="bg-white border rounded-xl p-5"><div className="text-sm text-slate-500">Successful</div><div className="text-2xl font-bold mt-2">{successful.length}</div></div><div className="bg-white border rounded-xl p-5"><div className="text-sm text-slate-500">Failed</div><div className="text-2xl font-bold mt-2">{failed.length}</div></div><div className="bg-white border rounded-xl p-5"><div className="text-sm text-slate-500">Pending</div><div className="text-2xl font-bold mt-2">{pending.length}</div></div></div>
 <div className="bg-white border rounded-xl overflow-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{['Date','Name','Amount','Currency','Fund','Status','Reference','Action'].map(h=><th key={h} className="p-3 text-left whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{rows.map(x=>{const status=String(x.status).toLowerCase();const ok=['success','paid'].includes(status);const bad=['failed','cancelled','abandoned'].includes(status);return <tr key={x.id} className="border-t"><td className="p-3">{new Date(x.created_at).toLocaleString()}</td><td className="p-3">{x.name||'—'}</td><td className="p-3">{Number(x.amount).toLocaleString()}</td><td className="p-3">{x.currency}</td><td className="p-3">{x.fund}</td><td className="p-3"><span className={`px-2 py-1 rounded-full text-xs ${ok?'bg-green-100 text-green-700':bad?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}`}>{x.status}</span></td><td className="p-3 font-mono text-xs">{x.reference||'—'}</td><td className="p-3">{x.reference&&!ok&&!bad?<button onClick={()=>verify(x.reference!)} disabled={verifying===x.reference} className="text-blue-700 inline-flex items-center gap-1"><ShieldCheck size={15}/>{verifying===x.reference?'Checking…':'Verify'}</button>:ok?'Verified':bad?'Failed':'—'}</td></tr>})}</tbody></table>{loading&&<div className="p-5 text-center text-slate-500">Loading…</div>}</div></div>
}
