import { FormEvent, useEffect, useState } from 'react'
import { Plus, Save, Trash2 } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { defaultHomeContent, type HomeContent as HomeContentType } from '../lib/homeContent'
export default function HomeContent(){
 const [form,setForm]=useState<HomeContentType>(defaultHomeContent); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('')
 useEffect(()=>{(async()=>{const{data}=await supabase.from('site_settings').select('key,value').in('key',['daily_verse_text','daily_verse_ref','memory_verse_text','memory_verse_ref','announcements']);const n={...defaultHomeContent,announcements:[...defaultHomeContent.announcements]};for(const r of data||[]){if(r.key==='daily_verse_text')n.daily_verse_text=String(r.value||'');if(r.key==='daily_verse_ref')n.daily_verse_ref=String(r.value||'');if(r.key==='memory_verse_text')n.memory_verse_text=String(r.value||'');if(r.key==='memory_verse_ref')n.memory_verse_ref=String(r.value||'');if(r.key==='announcements'&&Array.isArray(r.value))n.announcements=r.value}setForm(n)})()},[])
 const save=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMsg('');try{const rows=[['daily_verse_text',form.daily_verse_text],['daily_verse_ref',form.daily_verse_ref],['memory_verse_text',form.memory_verse_text],['memory_verse_ref',form.memory_verse_ref],['announcements',form.announcements]];for(const[key,value]of rows){const{error}=await supabase.from('site_settings').upsert({key,value,updated_at:new Date().toISOString()});if(error)throw error}setMsg('Home page content saved successfully.')}catch(err){setMsg(err instanceof Error?err.message:'Unable to save home content')}finally{setBusy(false)}}
 const updateA=(i:number,k:string,v:string)=>setForm(f=>({...f,announcements:f.announcements.map((a,j)=>j===i?{...a,[k]:v}:a)}));
 return <div><h1 className="text-2xl font-bold">Home Page Content</h1><p className="text-slate-500 mt-1">Update the Bible verse, memory verse and announcements displayed on the public home page.</p><form onSubmit={save} className="mt-6 max-w-4xl space-y-5"><section className="bg-white border rounded-xl p-6 space-y-4"><h2 className="font-semibold">Daily Bible Verse</h2><textarea required rows={4} className="w-full border rounded-lg px-3 py-2.5" value={form.daily_verse_text} onChange={e=>setForm({...form,daily_verse_text:e.target.value})}/><input required className="w-full border rounded-lg px-3 py-2.5" placeholder="Reference e.g. John 3:16" value={form.daily_verse_ref} onChange={e=>setForm({...form,daily_verse_ref:e.target.value})}/></section><section className="bg-white border rounded-xl p-6 space-y-4"><h2 className="font-semibold">Weekly Memory Verse</h2><textarea required rows={4} className="w-full border rounded-lg px-3 py-2.5" value={form.memory_verse_text} onChange={e=>setForm({...form,memory_verse_text:e.target.value})}/><input required className="w-full border rounded-lg px-3 py-2.5" placeholder="Reference" value={form.memory_verse_ref} onChange={e=>setForm({...form,memory_verse_ref:e.target.value})}/></section><section className="bg-white border rounded-xl p-6"><div className="flex justify-between items-center mb-4"><h2 className="font-semibold">Announcements</h2><button type="button" onClick={()=>setForm(f=>({...f,announcements:[...f.announcements,{title:'',date:'',text:''}]}))} className="text-sm text-blue-700 flex items-center gap-1"><Plus size={15}/> Add</button></div>{form.announcements.map((a,i)=><div key={i} className="border rounded-lg p-4 mb-3 space-y-2"><div className="flex gap-2"><input className="flex-1 border rounded-lg px-3 py-2" placeholder="Title" value={a.title} onChange={e=>updateA(i,'title',e.target.value)}/><input className="w-32 border rounded-lg px-3 py-2" placeholder="Date" value={a.date} onChange={e=>updateA(i,'date',e.target.value)}/><button type="button" onClick={()=>setForm(f=>({...f,announcements:f.announcements.filter((_,j)=>j!==i)}))}><Trash2 size={16}/></button></div><textarea rows={2} className="w-full border rounded-lg px-3 py-2" placeholder="Announcement details" value={a.text} onChange={e=>updateA(i,'text',e.target.value)}/></div>)}</section>{msg&&<div className="p-3 rounded-lg border bg-slate-50 text-sm">{msg}</div>}<button disabled={busy} className="bg-blue-700 text-white px-4 py-2.5 rounded-lg flex items-center gap-2 disabled:opacity-50"><Save size={17}/>{busy?'Saving…':'Save home content'}</button></form></div>
}
