import { FormEvent, useEffect, useState } from 'react'
import { Plus, Save, Trash2, Upload, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { uploadMedia, removeMediaByUrl } from '../lib/storage'

type Social = { label:string; url:string; icon:string }
type Pastor = { id:string; name:string; role:string; bio:string; image_url:string|null; socials:Social[]; sort_order:number; published:boolean }
const blank: Omit<Pastor,'id'> = { name:'', role:'', bio:'', image_url:null, socials:[], sort_order:0, published:true }
const icons=['facebook','instagram','twitter','youtube','linkedin','website']
export default function Pastors(){
 const [items,setItems]=useState<Pastor[]>([]); const [editing,setEditing]=useState<any>(null); const [file,setFile]=useState<File|null>(null); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false)
 const load=async()=>{const{data,error}=await supabase.from('pastors').select('*').order('sort_order');if(error)setMsg(error.message);else setItems((data||[]).map((x:any)=>({...x,socials:Array.isArray(x.socials)?x.socials:[]})))}
 useEffect(()=>{load()},[])
 const save=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMsg('');try{let image=editing.image_url;if(file) image=await uploadMedia(file,'pastors'); const payload={name:editing.name.trim(),role:editing.role.trim(),bio:editing.bio,image_url:image||null,socials:editing.socials,sort_order:Number(editing.sort_order)||0,published:editing.published,updated_at:new Date().toISOString()}; const q=editing.id?supabase.from('pastors').update(payload).eq('id',editing.id):supabase.from('pastors').insert(payload);const{error}=await q;if(error)throw error;setEditing(null);setFile(null);await load();setMsg('Pastor saved successfully.')}catch(err){setMsg(err instanceof Error?err.message:'Unable to save pastor')}finally{setBusy(false)}}
 const remove=async(p:Pastor)=>{if(!confirm(`Delete ${p.name}?`))return;const{error}=await supabase.from('pastors').delete().eq('id',p.id);if(error)setMsg(error.message);else{await removeMediaByUrl(p.image_url);load()}}
 const addSocial=()=>setEditing((x:any)=>({...x,socials:[...x.socials,{label:'Instagram',url:'',icon:'instagram'}]}))
 return <div><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Pastors</h1><p className="text-slate-500 mt-1">Manage pastor profiles, photos, biographies and social links shown on the public Pastors page.</p></div><button onClick={()=>{setEditing({...blank,socials:[]});setFile(null)}} className="bg-blue-700 text-white px-4 py-2.5 rounded-lg flex items-center gap-2"><Plus size={17}/> Add pastor</button></div>
 {msg&&<div className="mt-4 p-3 rounded-lg border bg-white text-sm">{msg}</div>}
 <div className="mt-6 grid gap-4">{items.map(p=><div key={p.id} className="bg-white border rounded-xl p-4 flex flex-col md:flex-row gap-4 md:items-center"><div className="w-20 h-20 rounded-xl overflow-hidden bg-slate-100 shrink-0">{p.image_url&&<img src={p.image_url} className="w-full h-full object-cover"/>}</div><div className="flex-1"><div className="font-semibold">{p.name}</div><div className="text-sm text-blue-700">{p.role}</div><div className="text-sm text-slate-500 line-clamp-2">{p.bio}</div><div className="text-xs text-slate-400 mt-1">{p.socials.map(s=>s.label).join(' · ')||'No social links'}</div></div><div className="flex gap-2"><button onClick={()=>{setEditing({...p});setFile(null)}} className="border rounded-lg px-3 py-2 text-sm">Edit</button><button onClick={()=>remove(p)} className="border rounded-lg px-3 py-2 text-sm text-red-600"><Trash2 size={16}/></button></div></div>)}</div>
 {editing&&<div className="fixed inset-0 bg-black/40 z-50 p-4 overflow-y-auto"><form onSubmit={save} className="bg-white max-w-2xl mx-auto mt-8 rounded-2xl p-6 space-y-4"><div className="flex justify-between items-center"><h2 className="text-xl font-bold">{editing.id?'Edit pastor':'Add pastor'}</h2><button type="button" onClick={()=>setEditing(null)}><X/></button></div><input required placeholder="Name" className="w-full border rounded-lg px-3 py-2.5" value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/><input required placeholder="Role" className="w-full border rounded-lg px-3 py-2.5" value={editing.role} onChange={e=>setEditing({...editing,role:e.target.value})}/><textarea required rows={6} placeholder="Biography" className="w-full border rounded-lg px-3 py-2.5" value={editing.bio} onChange={e=>setEditing({...editing,bio:e.target.value})}/><label className="block text-sm font-medium">Pastor photo<label className="mt-1 border rounded-lg p-3 flex items-center gap-2 cursor-pointer"><Upload size={16}/>{file?.name||'Choose image'}<input hidden type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{editing.image_url&&<img src={editing.image_url} className="mt-2 w-24 h-24 rounded-lg object-cover"/>}</label><div><div className="flex items-center justify-between mb-2"><h3 className="font-semibold">Social links</h3><button type="button" onClick={addSocial} className="text-sm text-blue-700">+ Add social</button></div>{editing.socials.map((s:Social,i:number)=><div key={i} className="grid grid-cols-[110px_1fr_auto] gap-2 mb-2"><select className="border rounded-lg px-2" value={s.icon} onChange={e=>{const a=[...editing.socials];a[i]={...a[i],icon:e.target.value,label:e.target.value[0].toUpperCase()+e.target.value.slice(1)};setEditing({...editing,socials:a})}}>{icons.map(x=><option key={x}>{x}</option>)}</select><input className="border rounded-lg px-3 py-2" placeholder="https://..." value={s.url} onChange={e=>{const a=[...editing.socials];a[i]={...a[i],url:e.target.value};setEditing({...editing,socials:a})}}/><button type="button" onClick={()=>setEditing({...editing,socials:editing.socials.filter((_:Social,j:number)=>j!==i)})}><Trash2 size={16}/></button></div>)}</div><div className="grid grid-cols-2 gap-3"><input type="number" className="border rounded-lg px-3 py-2.5" value={editing.sort_order} onChange={e=>setEditing({...editing,sort_order:e.target.value})} placeholder="Display order"/><label className="flex items-center gap-2"><input type="checkbox" checked={!!editing.published} onChange={e=>setEditing({...editing,published:e.target.checked})}/> Published</label></div><button disabled={busy} className="bg-blue-700 text-white px-4 py-2.5 rounded-lg flex gap-2 items-center disabled:opacity-50"><Save size={17}/>{busy?'Saving…':'Save pastor'}</button></form></div>}
 </div>
}
