import { FormEvent, useEffect, useState } from 'react'
import { Pencil, Plus, Trash2 } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Sermon } from '../types'

const empty = {title:'',speaker:'',date:'',category:'',scripture:'',description:'',image_url:'',youtube_id:'',video_url:'',audio_url:'',notes_url:'',featured:false,published:true}

export default function Sermons(){
  const [items,setItems]=useState<Sermon[]>([]); const [form,setForm]=useState<any>(empty); const [editing,setEditing]=useState<string|null>(null); const [open,setOpen]=useState(false)
  async function load(){const {data}=await supabase.from('sermons').select('*').order('date',{ascending:false});setItems((data??[]) as Sermon[])}
  useEffect(()=>{load()},[])
  async function save(e:FormEvent){e.preventDefault();const payload={...form,image_url:form.image_url||null,youtube_id:form.youtube_id||null,video_url:form.video_url||null,audio_url:form.audio_url||null,notes_url:form.notes_url||null}; if(editing) await supabase.from('sermons').update(payload).eq('id',editing); else await supabase.from('sermons').insert(payload);setForm(empty);setEditing(null);setOpen(false);await load()}
  async function del(id:string){if(confirm('Delete this sermon?')){await supabase.from('sermons').delete().eq('id',id);await load()}}
  return <div><div className="flex justify-between items-center mb-6"><div><h1 className="text-2xl font-bold">Sermons</h1><p className="text-slate-500">Manage videos, audio and sermon information.</p></div><button onClick={()=>{setForm(empty);setEditing(null);setOpen(true)}} className="bg-blue-700 text-white px-4 py-2 rounded-lg flex gap-2 items-center"><Plus size={18}/> Add sermon</button></div>
    <div className="bg-white border rounded-xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="text-left p-3">Title</th><th className="text-left p-3">Speaker</th><th className="text-left p-3">Date</th><th className="text-left p-3">Status</th><th className="p-3"></th></tr></thead><tbody>{items.map(x=><tr key={x.id} className="border-t"><td className="p-3 font-medium">{x.title}</td><td className="p-3">{x.speaker}</td><td className="p-3">{x.date}</td><td className="p-3">{x.published?'Published':'Draft'}</td><td className="p-3 flex gap-2 justify-end"><button onClick={()=>{setForm({...x});setEditing(x.id);setOpen(true)}}><Pencil size={17}/></button><button onClick={()=>del(x.id)}><Trash2 size={17}/></button></td></tr>)}</tbody></table></div>
    {open&&<div className="fixed inset-0 bg-black/40 z-50 p-4 overflow-auto"><form onSubmit={save} className="bg-white max-w-2xl mx-auto my-8 rounded-2xl p-6 space-y-3"><h2 className="text-xl font-bold">{editing?'Edit':'Add'} sermon</h2>{[['title','Title'],['speaker','Speaker'],['date','Date'],['category','Category'],['scripture','Scripture'],['image_url','Thumbnail URL'],['youtube_id','YouTube video ID'],['video_url','Direct video URL'],['audio_url','Audio URL'],['notes_url','Notes URL']].map(([k,l])=><label key={k} className="block text-sm">{l}<input className="mt-1 w-full border rounded-lg px-3 py-2" value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="block text-sm">Description<textarea className="mt-1 w-full border rounded-lg px-3 py-2" rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="flex gap-5"><label><input type="checkbox" checked={!!form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured</label><label><input type="checkbox" checked={!!form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Published</label></div><div className="flex justify-end gap-2 pt-3"><button type="button" onClick={()=>setOpen(false)} className="px-4 py-2 border rounded-lg">Cancel</button><button className="px-4 py-2 bg-blue-700 text-white rounded-lg">Save</button></div></form></div>}
  </div>
}
